"""Download personal weapon renders from the Helldivers Wiki as WebP thumbnails.

Reads the infobox `image=` of each roster page in db/source/wiki_pages.json,
asks the wiki API for a 480 px thumbnail, and writes
dist/assets/weapons/<id>.webp plus dist/data/weapon-images.js.

Usage: python scripts/tools/fetch-weapon-images.py   (requires Pillow with WebP)
"""
import hashlib, io, json, pathlib, re, subprocess, time, urllib.parse, urllib.request

from PIL import Image

root = pathlib.Path(__file__).resolve().parents[2]
out_dir = root / 'dist' / 'assets' / 'weapons'
module = root / 'dist' / 'data' / 'weapon-images.js'
API = 'https://helldivers.wiki.gg/api.php'
UA = 'HD2FieldGuide/2.0 (fan site data check; contact via github jj-dot-eng)'
WIDTH = 480

def get(url):
    request = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()

pages = json.loads((root / 'db' / 'source' / 'wiki_pages.json').read_text(encoding='utf-8'))['pages']
ids = json.loads(subprocess.run(['node', '--input-type=module', '-e',
    'import { weapons } from "./db/weapons.js"; console.log(JSON.stringify(Object.fromEntries(weapons.map(w => [w.en, w.id]))))'],
    cwd=root, capture_output=True, text=True, check=True).stdout)

files = {}
for title, page in pages.items():
    match = re.search(r'\n\s*\|\s*image\s*=\s*([^\n|]*)', page['wikitext'] or '')
    name = match.group(1).replace('{{PAGENAME}}', title).strip() if match else ''
    if name: files[title] = re.sub(r'^\[\[File:|\]\]$', '', name).strip()

info = {}
titles = sorted(set(files.values()))
for start in range(0, len(titles), 50):
    batch = titles[start:start + 50]
    query = urllib.parse.urlencode({'action': 'query', 'format': 'json', 'prop': 'imageinfo', 'iiprop': 'url|sha1|size',
                                    'iiurlwidth': WIDTH, 'titles': '|'.join('File:' + t for t in batch)})
    data = json.loads(get(f'{API}?{query}'))
    normalized = {n['to']: n['from'] for n in data['query'].get('normalized', [])}
    for p in data['query']['pages'].values():
        if p.get('imageinfo'):
            info[normalized.get(p['title'], p['title'])[5:]] = p['imageinfo'][0]
    time.sleep(0.3)

out_dir.mkdir(parents=True, exist_ok=True)
entries, missing = {}, []
for title in sorted(files):
    meta = info.get(files[title])
    if not meta:
        missing.append(title); continue
    raw = get(meta.get('thumburl') or meta['url'])
    time.sleep(0.2)
    with Image.open(io.BytesIO(raw)) as image:
        image = image.convert('RGBA')
        box = image.getbbox()  # trim transparent margins so renders line up
        if box: image = image.crop(box)
        buffer = io.BytesIO()
        image.save(buffer, 'WEBP', quality=86, method=6)
        width, height = image.size
    target = out_dir / f'{ids[title]}.webp'
    target.write_bytes(buffer.getvalue())
    entries[ids[title]] = {
        'src': f'./assets/weapons/{target.name}', 'width': width, 'height': height,
        'file': files[title], 'source': 'https://helldivers.wiki.gg/wiki/File:' + urllib.parse.quote(files[title].replace(' ', '_')),
        'sourceSha1': meta.get('sha1'), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest(),
    }

body = ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}' for k, v in sorted(entries.items()))
module.write_text('// Generated by scripts/tools/fetch-weapon-images.py from Helldivers Wiki weapon renders.\n'
                  f'export const weaponImages = {{\n{body},\n}};\n', encoding='utf-8', newline='\n')
print(f'{len(entries)} images written; missing: {missing}')
